#!/usr/bin/env bash
# Summary: Find <filename> from current working directory or from parent dir
# Usage: waz-find-config-file <filename>
set -e
[ -n "$WAZ_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  local config_file="$2"
  while [ -n "$root" ]; do
    if [ -e "${root}/${config_file}" ]; then
      echo "${root}/${config_file}"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$PWD" "$1"
